name: tomobar
channels:
  - conda-forge
dependencies:
  - conda-forge::numpy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::setuptools
  - conda-forge::ipython
  - conda-forge::conda-build
  - conda-forge::anaconda-client
