name: tomobar
channels:
  - conda-forge
  - astra-toolbox
  - httomo
dependencies:
  - astra-toolbox::astra-toolbox
  - httomo::ccpi-regularisation-cupy
  - httomo::ccpi-regulariser
  - conda-forge::cupy
  - conda-forge::numpy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::setuptools
  - conda-forge::ipython

