name: tomobar
channels:
  - conda-forge
  - anaconda
  - astra-toolbox
dependencies:
  - conda-forge::numpy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::setuptools
  - anaconda::ipython  
  - anaconda::conda-build
  - anaconda::anaconda-client
  - astra-toolbox::astra-toolbox
