{% set name = "tomobar" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python>=3.9
    - numpy
    - setuptools
    - pillow
    - pytest

test:
  requires:
    - pip
    - pytest
  imports:
    - tomobar
    - tomobar.supp
  commands:
    - pip check
requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python={{ python }}
    - numpy={{ numpy }}
    - setuptools
    - pillow
    - scikit-image
    - pytest

about:
  home: https://github.com/dkazanc/ToMoBAR
  summary: 'TOmographic MOdel-BAsed Reconstruction (ToMoBAR) software'
  description: |
    A collection of direct and iterative methods for parallel beam tomography
extra:
  recipe-maintainers:
    - dkazanc