{% set name = "tomobar" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] }}

source:
  path: ../

build:
  preserve_egg_dir: False
  number: 0

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest
    
requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - setuptools
    - scipy
    - pillow
    - scikit-image
    - pytest

about:
  home: https://github.com/dkazanc/ToMoBAR
  summary: 'TOmographic MOdel-BAsed Reconstruction (ToMoBAR) software'
  description: |
    A collection of direct and iterative methods for parallel beam tomography
extra:
  recipe-maintainers:
    - dkazanc
