name: tomobar_conda_upload

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies with Conda
      run: |
        $CONDA/bin/conda env update --file conda-recipe/environment/environment.yml --name base
        $CONDA/bin/conda list
        

    - name: Decrypt a secret
      run: ./.scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Upload the tested package to conda cloud
      env:
        LABEL: main
      run: |
        chmod +x ./.scripts/conda_upload.sh
        ./.scripts/conda_upload.sh
