name: tomobar_conda_upload

on: [push, pull_request, pull_request_target]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies with Conda
        run: |
          $CONDA/bin/conda env update --file conda-recipe/environment/environment.yml --name base
          conda config --set anaconda_upload no
          export VERSION=`date +%Y.%m` 

      - name: Decrypt a secret
        run: ./.scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Upload the tested package to conda cloud
        run: |
          chmod +x ./.scripts/conda_upload.sh
          ./.scripts/conda_upload.sh
